import NavigationFoodMenu from "@/components/publicComponents/foodMenu/NavigationFoodMenu";
import { Box, Container } from "@mui/material";
import { grey } from "@mui/material/colors";

export const metadata = {
  title: "Food Menu",
  description: "Generated by Mohsen Shahrokhi",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Container
      maxWidth={"desktop"}
      sx={{
        justifyContent: "center",
        alignItems: "center",
        display: "flex",
        height: "100%",
        width: "100%",
        marginRight: 5,
        marginLeft: 5,
      }}
      component={"div"}
    >
      <Box
        sx={{
          justifyContent: "space-between",
          alignItems: "center",
          display: "flex",
          flexDirection: "column",
          paddingRight: 0,
          paddingLeft: 0,
          height: "100%",
          width: "100%",
          borderLeft: 1,
          borderRight: 1,
          borderTop: 40,
          borderColor: grey[300],
          borderTopLeftRadius: 15,
          borderTopRightRadius: 15,
          boxShadow: 3,
          // marginTop: 3,
        }}
      >
        <Box
          sx={{
            display: "flex",
            width: "100%",
            overflowY: "auto",
          }}
          component={"div"}
        >
          {children}
        </Box>
        <Box
          sx={{
            display: "flex",
            width: "100%",
            bgcolor: grey[300],
            height: "3rem",
          }}
          component={"div"}
        >
          <NavigationFoodMenu />
        </Box>
      </Box>
    </Container>
  );
}
