import { Box } from "@mui/material";

export const metadata = {
  title: "Food Menu",
  description: "Generated by Mohsen Shahrokhi",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Box
      component={"div"}
      className=" flex flex-col w-full h-screen justify-between dark:bg-zinc-900 dark:text-zinc-100"
    >
      <Box
      component={"div"} className=" flex-1">{children}</Box>
    </Box>
  );
}
