// import BodyFoodMenu from "@/components/publiCcomponents/foodMenu/BodyFoodMenu"
// import FoodMenu from "@/components/publiCcomponents/foodMenu/FoodMenu"
// import NavigationFoodMenu from "@/components/publiCcomponents/foodMenu/NavigationFoodMenu"
// import { CAT } from "@/type"
// import axios from "axios"
// import { TProductSchema } from "@/ZSchemas/ProductSchema";
// import { getProducts } from "@/actions/product";
// import BodyFoodMenu from "@/components/publicComponents/foodMenu/BodyFoodMenu";
// import queryString from "query-string";

export const metadata = {
  title: "Food Menu",
  description: "Generated by Mohsen Shahrokhi",
};

// type Data = {
//   products: TProductSchema[];
//   success: boolean;
//   qtt: number;
// };

// async function getData() {
//   const params = {
//     populate:
//       "category.name,category.images,category.latinName,author.displayName",
//   };

//   const stringifyParams = queryString.stringify(params);

//   const products = await getProducts(stringifyParams);

//   return products as Data;
// }

export default async function MenuPage({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  // const { products } = await getData();

  return (
    <div className="flex-1">
      {/* <BodyFoodMenu productsString={JSON.stringify(products)} /> */}
    </div>
  );
}
