import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeDirection from "@/utils/ThemeProvider";
import AuthProvider from "@/utils/AuthProvider";
import ToustProvider from "@/utils/ToustProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa-IR">
      <body >
        <ThemeDirection>
          <AuthProvider>
            <ToustProvider>
              {children}
            </ToustProvider>
          </AuthProvider>
        </ThemeDirection>
      </body>
    </html>
  );
}
