import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ThemeDirection from "@/utils/ThemeProvider"
import AuthProvider from "@/utils/AuthProvider"
import ToustProvider from "@/utils/ToustProvider"
// import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const vazirFont = localFont({
//   src: [
//     {
//       path: '../public/font/VazirmatnRegular.woff2',
//       weight: '800'
//     }
//   ],
//   variable: '--font-VazirmatnRegular',
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html dir="rtl" lang="fa-IR">
      <body className=" flex h-screen w-full" >
        <ThemeDirection>
          <AuthProvider>
            <ToustProvider>
              {children}
            </ToustProvider>
          </AuthProvider>
        </ThemeDirection>
      </body>
    </html>
  );
}
